### PR TITLE
pb files update && goprotobuf google code fix

### PR DESCRIPTION
**Pull request by fengjingchao**
1. protobuf go plugin and grpc changes. Let's upgrade it.
2. the google code goprotobuf is moved to github. But the hdfs dep doesn't upgrade to it. I have a temporary fix to hack GOPATH and download repo manually.

### CODE REVIEW

**Comment by fengjingchao** [comment]
The test isn't good. I don't know why it shows green. Let me handle this and then merge this myself.

**Comment by fengjingchao** [comment]
I will keep track of https://github.com/colinmarc/hdfs/issues/13
If he doesn't respond, then we can either fork ourselves or upload the code manually.

**Comment by fengjingchao** [comment]
OK. now it should work.

**Comment by BaiGang** [comment]
LGTM.

**Pull request merged**
