### PR TITLE
Revert "Linktype topology test"

### PR DESCRIPTION
**Pull request by fengjingchao**
Reverts taskgraph/taskgraph#132

### CODE REVIEW

**Comment by xiaoyunwu** [comment]
What is wrong with this Again？

Hongchao Deng <notifications@github.com>于2015年6月20日星期六写道：

**Comment by fengjingchao** [comment]
The problems comes with the change from topology to the linkage mapping.
What's the point to change that?

**Comment by xiaoyunwu** [comment]
I think we have went through this before.

This change is needed for the following reason:

As we factor out epoch from api to implementation, and allow developer to
build their application by picking different components. We run into case
where connections (Let me use this undefined term, but it is close to
topology) can be defined by different parties:
a. Epoch implementation might define a star like topology where every one
talk to task 0 for synchronization. This topology is implemented once by
us.
b. Application might need to have application depended connections that
they needed.

So without this change, developer will always need to aware the topology
epoch implementation might need since they need to include such code in the
same file or so. And this can be dangerous. The change that Pluto did here
is so that it allows different slicd/view of topology can be defined
separately, that way, developer doesn't have chance to mess it up for epoch
related topology.

Xiaoyun

**Comment by fengjingchao** [comment]
Look at the current interface:
https://github.com/taskgraph/taskgraph/blob/b1d289b237c26f0dc4077e33bbdef4e151ba8d1d/framework_interface.go#L19

What to watch is being set up at the beginning. Once epoch is moved out, there is NO WAY to change topology (what to watch) along with epoch because epoch becomes a user concept. We can achieve it only by passing the capability of deleting and adding "what to watch" to users.

**Comment by fengjingchao** [comment]
This thing would be fixed as discussed in #129

**Pull request closed without merging**
