### PR TITLE
newLinkTyepTopology : Initialize with old linkTypeTology branch

### PR DESCRIPTION
**Pull request by plutoshe**
rebase on head of master

### CODE REVIEW

**Comment by fengjingchao** [comment]
Sorry for the late response on this.

I strongly disagree w/ this change. It is unnecessary. It complicates the code by adding another layer of linkage mapping. Not even mention that it adds badly reviewed code:

https://github.com/taskgraph/taskgraph/blob/a1b394d0a9e471048bc8e80123954d97a1a97efe/example/bwmf/bwmf/main.go#L13

We needs this layer of abstraction of topology so that everything related to what to watch lies inside. As we're moving epoch out, and later work on discussing and designing our new reliable message passing, having topology abstraction should make the change cleaner.

**Comment by xiaoyunwu** [comment]
what is ur concern? It is not clear from the email
Xiaoyun

Hongchao Deng <notifications@github.com>于2015年6月20日星期六写道：

**Comment by fengjingchao** [comment]
What's the point for the change?
Whatever to watch should be contained inside the topology abstraction. Now the code is tightly coupled to the framework.

**Comment by xiaoyunwu** [comment]
This doesn't change any thing, framework now used used different ways to
setup watches.

in the past, the map in implemented in the topology, but is exposed to
framework, now, the map is maintained by framework, but it do not really
reveal anything else.

As I said in the other email thread, this change will make is easier to
componenterize different things. As developer does have to maintain the
entire topology.

Xiaoyun

**Comment by fengjingchao** [comment]
I think your point is that users should be able to dynamically change the topology.
However, as I mentioned in another thread, this impl. still sets up STATIC "what to watch".

We should revert this change either way because it is the wrong implementation.

**Comment by fengjingchao** [comment]
Furthermore, it ties a map into framework which makes further refactoring work (which we might do a lot) harder.

**Comment by xiaoyunwu** [comment]
If I remember it correctly, the linktypes will be static, by the connection
with given linktype can change for different epoch.

So, parameter linktype might talk to different nodes for parameters, but
there will always be a parameter linktype.

Xiaoyun

**Comment by xiaoyunwu** [comment]
Can you first try to understand why we do this? If you can come up a better
solution to the problem, let me know. I am curious.

Yes, we are moving some implementation from topology to framework, but I
don't see why this makes refactoring harder.

Xiaoyun

**Comment by fengjingchao** [comment]
The watch mechanism is implemented by the framework not user.
If the framework has no perception of epoch, there is not difference from previous single topology interface.

**Comment by fengjingchao** [comment]
The solution is obvious and we have discussed so many times that I thought we have consensus on this.
The epoch is going to be moved out. We need to expose the capability of adding and removing "what to watch" to user instead of single, static topology (or this no different linkage map).

**Comment by fengjingchao** [comment]
I think we can keep the change since reverting now is not safe option (many commits after it).

The point of discussion here is that the implementation is still WRONG. We should be aware of it and fix it later. Another point is that we should be more patient in waiting review cycles.

**Comment by xiaoyunwu** [comment]
Hi, Hongchao,

The implementation of epoch will be moved out, for sure, but it still here.

More importantly, regardless where do we keep epoch implementation, it will
be a component that we provide to user, so implementation of watching will
need to go somewhere. I can agree that current change is not well thought
for the eventual scenarios, but I don't see anything wrong with it. It is a
simple change that make current implementation less questionable.

Can you try to point out how we might solve the problems that I stated in
one of the mail why we make this change? I think by stay concrete we might
communicate better.

Xiaoyun

**Comment by xiaoyunwu** [comment]
Can you be a bit concrete on why this is wrong?

I just did not see it. The change is designed to fix an issue when one
application might use multiple topologies to achieve its goal. Instead of
asking developer copy and paste different code into one place, this allow
each developer only worry their need when it comes to topology side. I feel
this change did solve the problem we intended to solve.

Am I missing something here?

Xiaoyun

**Comment by fengjingchao** [comment]
Okay. I think we need to make this more concrete so that everyone agrees.

## Problem Description
When epoch changes, "what to watch" could change. For example, in epoch 1, A is watching notification from B, then in epoch 2, A wants to watch from C.

The watch mechanism should also be implemented by framework because we want to hide this details.

## Solution
Previously, our framework has perception of epoch. Framework realizes any epoch change and safely changes "what to watch" at the beginning of each epoch. As we're moving epoch out of framework, now the topology couldn't change because there's no epoch change in framework. Instead of asking users to give us a definition of "what to watch" at the bootstrapping phase, we should expose the capability of adding and removing "what to watch" to users. Users should manage the "links" and handle any synchronization failure.

I don't want to argue why this change doesn't solve any problem and is no different (or worse) than previous thing. This is just so obvious if you review the code carefully. I will push new proposal to completely address this problem.

**Comment by xiaoyunwu** [comment]
Hi, Hongchao,

I think you are right, that the change in question doesn't make thing worse
or better (beside it now allow topology needed by one application
implemented by multiple parties, and they don't need to know each other).
It does not try to any problem beside this.

It is unfortunate that such a small change has to touch a lot of files.

Xiaoyun

**Comment by fengjingchao** [comment]
Let me summarize the purpose of this PR here:

It tries to further refactor the topology and separate out more reusable topologies.

This change complicates the logic and breaks our encapsulation. We should continue our design phase though and move out epoch as the priority.

**Comment by xiaoyunwu** [comment]
Sgtm

Hongchao Deng <notifications@github.com>于2015年6月20日星期六写道：

**Pull request merged**
