### PR TITLE
Update occupy

### PR DESCRIPTION
**Pull request by plutoshe**

### CODE REVIEW

**Comment by fengjingchao** [comment]
Can you write down some comments to explain the design?

**Comment by plutoshe** [comment]
For instance, in mapreduce framework, there are lots of mapper work. It's not practical to process a work for every task. So we need to implement a new mechanism---free work mechanism, a mapper task could constantly process mapper work.
More details could see mail of design docs of mapreduce.

I closed this pull request, maybe it is only necessary for mapreduce framework. 
And add this etcdutil pkg to mapreduce framework branch, comments on this part.

**Comment by fengjingchao** [comment]
Is it like a mapreduce service? I think Spark does something similar.
I haven't had time to take a look at the email that has design docs. I will take a look after May 4th, when we finish coreos talk.

**Comment by plutoshe** [comment]
It is like a mapreduce service. Thus it need to process a patch of work with different environment.

**Pull request closed without merging**
