### PR TITLE
[op] Projected Gradient Method based minimizer with unit tests

### PR DESCRIPTION
**Pull request by BaiGang**
Added two factory interfaces to create `Projection` and `ProjectedGradient`.

### CODE REVIEW

**Comment by xiaoyunwu** [comment]
Hi, Gang,

I will be in MS today, I am wondering whether you have time to sync up?

Thanks.

Xiaoyun

**Comment by BaiGang** [comment]
The build fails at:

```
FAIL	github.com/taskgraph/taskgraph/integration	7.769s
```

**Comment by fengjingchao** [comment]
This is not related.
The current code assumes no failure in network yet.

**Comment by xiaoyunwu** [comment]
I do not get it, why the test did not pass?

**Comment by BaiGang** [comment]
Seems the previous failure was due to occasional network issue. It's not what we will address here.

I modified the test driver script to include tests in `op` and it builds well.

**Pull request merged**
